### ISSUE TITLE
Feed_to_Anki.py: ssl.SSLError: [Errno 185090050] _ssl.c

### ISSUE THREAD

**Issue by JulyMorning** [luminousspice/anki-addons#1]
```
Traceback (most recent call last):
  File "aqt\addons.py", line 41, in loadAddons
  File "D:\system\documents\Anki\addons\Feed_to_Anki_for_Word_of_the_Day_RSS.py", line 32, in <module>
    import feed_to_anki.httplib2 as httplib2
ImportError: No module named feed_to_anki.httplib2
```

Like your concept very much, but there's some problem. Can you help to deal with it?

**Comment by JulyMorning** [comment]
Figured out, that it needs a feed_to_anki folder, but now I've got this:
```

Traceback (most recent call last):
  File "D:\system\documents\Anki\addons\Feed_to_Anki_for_Word_of_the_Day_RSS.py", line 70, in buildCards
    msg += buildCard(**feeds_info[i]) + "\n"
  File "D:\system\documents\Anki\addons\Feed_to_Anki_for_Word_of_the_Day_RSS.py", line 105, in buildCard
    (resp, data) = h.request(kw['URL'], "GET")
  File "D:\system\documents\Anki\addons\feed_to_anki\httplib2\__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "D:\system\documents\Anki\addons\feed_to_anki\httplib2\__init__.py", line 1404, in _request
    redirections=redirections - 1)
  File "D:\system\documents\Anki\addons\feed_to_anki\httplib2\__init__.py", line 1609, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "D:\system\documents\Anki\addons\feed_to_anki\httplib2\__init__.py", line 1351, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "D:\system\documents\Anki\addons\feed_to_anki\httplib2\__init__.py", line 1272, in _conn_request
    conn.connect()
  File "D:\system\documents\Anki\addons\feed_to_anki\httplib2\__init__.py", line 1036, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "D:\system\documents\Anki\addons\feed_to_anki\httplib2\__init__.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "D:\system\documents\Anki\addons\Feed_to_Anki_for_Word_of_the_Day_RSS.py", line 43, in bar
    return func(*args, **kw)
  File "ssl.py", line 381, in wrap_socket
  File "ssl.py", line 141, in __init__
ssl.SSLError: [Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
```

**Comment by JulyMorning** [comment]
Fixed by updating [httplib2](https://github.com/httplib2/httplib2). Thanks for your work, again, it's a great idea.

However it would be nice to have some GUI to add RSS channels, tags etc. It would be great to see it one day.
